version: '3'
services:

  postgresql:
    image: postgres:10.7
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: kms

  gunicorn:
    restart: always
    build: ./gunicorn/
    expose:
      - "8000"
    volumes:
      - "static:/static/"
      - "./gunicorn:/usr/src/app"
      - "./scripts:/scripts"
    depends_on:
      - postgresql
    command: ["/scripts/wait-for-it.sh", "postgresql:5432", "-s", "--", "bash", "./run.sh"]

  nginx:
    tty: true
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - "static:/www/static"
    links:
      - gunicorn


#  demo_client:
#    restart: always
#    build: ./demo-service
#    links:
#      - gunicorn
#      - demo_server
#    volumes:
#      - "./scripts:/scripts"
#    command: ["/scripts/wait-for-it.sh", "gunicorn:8000", "-s", "--", "python", "service.py"]

#  demo_server:
#    restart: always
#    expose:
#      - "9999"
#    ports:
#      - "9999:9999"
#    build: ./messenger
#    links:
#      - gunicorn
#    volumes:
#      - "./scripts:/scripts"
#    command: ["/scripts/wait-for-it.sh", "gunicorn:8000", "-s", "--", "python", "app.py"]

  redis:
    tty: true
    restart: always
    image: redis:latest

volumes:
  static:
