version: '3'
services:

  database:
    tty: true
    restart: always
    build: ./database/
    expose:
      - "5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"

  gunicorn:
    restart: always
    build: ./gunicorn/
    expose:
      - "8000"
    volumes:
      - "static:/static/"
      - "./gunicorn:/usr/src/app"
      - "./scripts:/scripts"
    links:
      - database
    command: ["/scripts/wait-for-it.sh", "database:5432", "-s", "--", "bash", "./run.sh"]

  nginx:
    tty: true
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - "static:/www/static"
    links:
      - gunicorn

  demo:
    restart: always
    build: ./demo-service
    links:
      - gunicorn
    volumes:
      - "./scripts:/scripts"
    command: ["/scripts/wait-for-it.sh", "gunicorn:8000", "-s", "--", "python", "service.py"]

volumes:
  static:
