# Generated by Django 3.0 on 2019-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='exception',
            field=models.BooleanField(default=False),
        ),
    ]
