# Generated by Django 3.0 on 2019-12-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accesslog_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='key',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='secret',
            name='value',
            field=models.CharField(max_length=32),
        ),
    ]
